# Generated by Django 2.2.1 on 2019-06-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandCallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('action', models.CharField(choices=[('SER', 'Serviço'), ('LAB', 'Laboratorio'), ('EQU', 'Equipamento')], max_length=3)),
                ('action_id', models.IntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_callback', to='demandai_administrador.Demand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AccessControl',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
