# Generated by Django 2.2.1 on 2019-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='icon',
            field=models.TextField(default=None),
        ),
    ]
