# Generated by Django 2.2.1 on 2019-11-21 17:13

import demandai_site.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('model', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.TextField()),
                ('codigo', models.CharField(choices=[('add_laboratory', 'Adicionar Laboratorio'), ('view_laboratory', 'Listar Laboratorio'), ('update_laboratory', 'Atualizar Laboratorio'), ('delete_laboratory', 'Deletar Laboratorio'), ('add_service', 'Adicionar Serviço'), ('view_service', 'Listar Serviço'), ('update_service', 'Atualizar Serviço'), ('delete_service', 'Deletar Serviço'), ('add_equipament', 'Adicionar Equipamento'), ('view_equipament', 'Listar Equipamento'), ('update_equipament', 'Atualizar Equipamento'), ('delete_equipament', 'Deletar Equipamento'), ('add_usuario', 'Adicionar Usuario'), ('view_usuario', 'Listar Usuario'), ('update_usuario', 'Atualizar Usuario'), ('delete_usuario', 'Deletar Usuario'), ('add_institution', 'Adicionar Instituição'), ('view_institution', 'Listar Instituição'), ('update_institution', 'Atualizar Instituição'), ('delete_institution', 'Deletar Instituição'), ('prospectar', 'Adicionar Instituição'), ('view_demand', 'Listar Instituição'), ('update_demand', 'Atualizar Instituição'), ('delete_demand', 'Deletar Instituição'), ('view_permission', 'Listar Instituição'), ('update_permission', 'Atualizar Instituição'), ('delete_institution', 'Deletar Instituição')], max_length=100)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='demandai_administrador.Content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='demand',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/demand_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar']), demandai_site.validators.validate_file_size]),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandai_administrador.Permission')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
