# Generated by Django 2.2.1 on 2019-05-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='demand',
            name='action',
            field=models.CharField(choices=[('SER', 'Serviço'), ('LAB', 'Laboratorio'), ('EQU', 'Equipamento')], max_length=3),
        ),
    ]
