# Generated by Django 2.2.1 on 2019-12-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandcb',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demandai_administrador.Demand'),
        ),
    ]
