# Generated by Django 2.2.1 on 2019-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0002_auto_20190618_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandcallback',
            name='prazo_feedback',
            field=models.DateTimeField(default=None),
        ),
    ]
