# Generated by Django 2.2.1 on 2019-05-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0002_auto_20190524_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
