# Generated by Django 2.2.1 on 2019-12-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0002_auto_20191205_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandcallback',
            name='demandcb',
        ),
        migrations.AddField(
            model_name='demandcallback',
            name='demand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandai_administrador.Demand'),
        ),
    ]
