# Generated by Django 2.2.1 on 2019-05-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0002_auto_20190529_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='user',
            new_name='profile',
        ),
    ]
