# Generated by Django 2.2.1 on 2019-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0003_demandcallback_prazo_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandcallback',
            name='prazo_feedback',
            field=models.DateTimeField(default='0000-00-00 00:00:00'),
        ),
    ]
