# Generated by Django 2.2.1 on 2019-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandai_administrador', '0005_auto_20190618_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandcallback',
            name='prazo_feedback',
            field=models.DateTimeField(null=True),
        ),
    ]
